[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools_scm[simple]>=6.2",
    "wheel",
    "build",
    "twine"
]
build-backend = "setuptools.build_meta"

[project]
name = "shakenfist_agent"
dynamic = ["version"]

description = "The in-guest agent for ShakenFist instances"
readme = "README.md"
requires-python = ">=3.0"
dependencies = [
    "click>=8.0.0",                     # bsd
    "oslo.concurrency",                 # apache2
    "distro",                           # apache2
    "linux-utils",                      # mit
    "psutil>5.9.0",                     # bsd
    "shakenfist-utilities",             # apache2
    "symbolicmode>=2.0",                # CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
    "setproctitle",                     # bsd

    "protobuf==5.29.5",                 # bsd
    "grpcio==1.70.0",                   # apache2
    "grpcio-status==1.70.0",            # apache2
    "grpcio-tools==1.70.0",             # apache2
    "googleapis-common-protos==1.70.0", # apache2
]

[project.urls]
"Homepage" = "https://shakenfist.com"
"Bug Tracker" = "https://github.com/shakenfist/agent-python/issues"

[project.scripts]
sf-agent = "shakenfist_agent.main:cli"

[tool.setuptools_scm]
git_describe_command = "git describe --dirty --tags --match v* --first-parent"
write_to = "shakenfist_agent/_version.py"

[project.optional-dependencies]
test = [
    "coverage",            # apache2
    "testtools",           # mit
    "mock",                # bsd
    "stestr",              # apache2
    "tox",                 # mit
    "flake8",              # mit
]